"""Your migration message here

Revision ID: fcff5d406c1b
Revises: 
Create Date: 2023-06-09 22:12:25.438467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcff5d406c1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'category_id')
    # ### end Alembic commands ###
